#!/bin/bash

# Dushan Karovich-Wynne
# e09962@rmit.edu.au

# Make sure tcsh is the active Shell, not using $SHELL as it only reflects the default shell to be invoked
ACTIVE_SHELL=`ps | grep tcsh | awk '{print $4}'`

if [ "$ACTIVE_SHELL" == "tcsh" ] ; then
    echo "WSWT Init Script (This sets up your PATH for WSWT)"
    echo "Your PATH variable is about to be PERMANENTLY changed, do you agree?" 
    echo "If so, please type 'yes' in lower case and hit enter."
    read confirmation
    if [ $confirmation == "yes" ] ; then
        sed '/^setenv PATH*/d' /home/stud/$USER/.cshrc > .tempcshrc
        mv .cshrc .cshrc.old && mv .tempcshrc .cshrc
        echo "setenv PATH "/bin:/etc:/usr/local/bin:/usr/openwin/bin:/usr/bin:/opt/SUNWspro/bin:/usr/ccs/bin:/usr/ucb:/usr/sbin/:/iweb/$USER/apache2/bin/"" >> .cshrc
        echo "It worked, you must now log out and log back in for the changes to become active"
    else
        echo "Goodbye..."
    fi
else
    echo "You are not using the default shell, please consult your tutor"
fi
